---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-nagios
    - role: coffeeitworks.ansible_nagios4_server_config
    - role: coffeeitworks.ansible_nagios4_checkmk_livestatus
    - role: ansible_nagios4_server_snmptrap
