---

- block:

  - name: Update hosts file
    lineinfile:
      dest="/etc/hosts" regexp="^{{ item.ip }}" line="{{ item.ip }}    {{ item.name }}"
    with_items: "{{ hosts_names }}"

  when: hosts_names

- name: ensure handlers runs before continue
  meta: flush_handlers

- block:

  - name: install pip packages
    pip:
      name: "{{ item }}"
      state: present
    with_items: "{{ nagios_update_hosts_pip_dependencies }}"

  - name: ensure nagios is started
    service: name="{{ nagios_service }}" state=started

  - name: wait for nagios socket to start
    wait_for:
      path: "{{ nagios_live_sock }}"

  - name: update hosts file from nagios config (fails if there is more than one host with same ip)
    script: nagios_update_hosts.py
    changed_when: false

  when: nagios_update_hosts_file

