# Variables

- import_tasks: multi_os.yml

# Installation
- name: Install SNMPTrap dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ snmptrap_dependencies }}"

# Configs

- name: Configure SNMP Templates
  template: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_items:
    - { src: 'snmptrapd.conf.j2', dest: '/etc/snmp/snmptrapd.conf' }
    - { src: 'snmptrap_service.cfg.j2', dest: "{{ nagios_config_cfg_dir }}/snmptrap_service.cfg" }
    - { src: 'snmptt.ini.j2', dest: "/etc/snmp/snmptt.ini" }
    - { src: 'snmp.conf.j2', dest: "/etc/snmp/snmp.conf" }
  notify: 
   - restart snmptt
   - restart snmpd
   - reload nagios
   - restart snmptrapd systemd

- name: copy snmptt translated MIBs
  copy:
    src: "snmptt/"
    dest: "/etc/snmp/"
    owner: "root"
    group: "root"
    mode: "755"
  notify:
    - restart snmptt

- name: copy other downloaded mibs
  copy:
    src: "mibs/"
    dest: "/usr/share/snmp/mibs/"
    owner: "root"
    group: "root"
    mode: "755"
  notify:
    - restart snmptt
    - restart snmpd

# During testing I have found problems compiling all those mibs and moved to netdisco mibs.
#- name: copy hp downloaded mibs
#  copy:
#    src: "mibs_available/hp/"
#    dest: "/usr/share/snmp/mibs/"
#    owner: "root"
#    group: "root"
#    mode: "755"
#  notify:
#    - restart snmptt
#    - restart snmpd

- name: clone mibs from netdisco-mibs (git)
  git:  repo="{{ snmp_netdisco_mibs_repo }}"
        dest="/var/lib/mibs/netdisco-mibs"
        update=yes
        force=yes
# restart of services is not required on this step so I have commented these lines.
#  notify:
#    - restart snmpd
#    - restart snmptt

# Executables

- name: Configure commands for Plugins
  copy:
    src: "files/submit_check_result"
    dest: "/usr/local/nagios/libexec/submit_check_result"
    owner: "root"
    group: "root"
    mode: "755"

- name: Configure commands for snmptt unknowns
  copy:
    src: "files/submit_check_result_unknowns"
    dest: "/usr/local/nagios/libexec/submit_check_result_unknowns"
    owner: "root"
    group: "root"
    mode: "755"


# Logrotate
# Not required, it's already on package

# The snmptrapd is not real systemd unit file, it is old /etc/init.d/snmptrapd
# but systemd creates automatically a unit for it to handle the script
- name: enable snmptrapd defaults
  lineinfile:
    dest: "{{ snmptrapd_default }}"
    regexp: 'TRAPDRUN='
    line: "TRAPDRUN=yes"
  notify: restart snmptrapd systemd

# Service handler:

- import_tasks: supervisor.yml
  when: snmptrap_config_supervisor

- name: start snmptrapd with systemd
  service:
    name: snmptrapd
    state: started
    enabled: yes
  when: not snmptrap_config_supervisor

# HOSTS file handle:
# DNS is enabled, the agent IP address is converted to a host name using a DNS lookup.
# see more in snmptt.ini original file

- import_tasks: hosts.yml
  tags: config_nagios
