# file: nagios-server/handlers/main.yml

# Supervisor must be restarted first
- name: restart supervisor
  service:
    name: supervisor
    state: restarted
    sleep: 5
  when: snmptrap_config_supervisor

- name: restart snmptt
  service:
    name: "snmptt"
    state: restarted

- name: restart snmpd
  service:
    name: "snmpd"
    state: restarted

- name: reload nagios
  service:
    name: "{{ nagios_service }}"
    state: reloaded

- name: restart snmptrapd
  supervisorctl:
    name: snmptrapd
    state: restarted
  when: snmptrap_config_supervisor

- name: restart snmptrapd systemd
  supervisorctl:
    name: snmptrapd
    state: restarted
  when: not snmptrap_config_supervisor

